import {UUID,DIGEST,parsePairing,SlopError} from './contracts.js';
import {mcpDraftPublicationView} from './mcp-publication-recovery.js';
export const PAIR_STORAGE='slop.pending-pair.v1';
export function validConnection(c){return UUID.test(c?.connection_id)&&typeof c.client_name==='string'&&c.client_name.length>0&&c.client_name.length<=60&&['pending','active','expired','revoked'].includes(c.status)&&Array.isArray(c.scopes)&&c.scopes.length===2&&c.scopes.includes('drafts:send')&&c.scopes.includes('drafts:status');}
export function validDraft(d){return UUID.test(d?.submission_id)&&UUID.test(d.project_id)&&DIGEST.test(d.digest)&&Number.isSafeInteger(d.revision)&&d.revision>0&&typeof d.name==='string'&&d.name.length>0&&d.name.length<=80&&/^mcp-[a-f0-9]{32}$/.test(d.slug)&&(!d.target_platform||['mobile','desktop','cross-platform'].includes(d.target_platform))&&['awaiting_confirmation','validating','ready'].includes(d.status);}
export function activeConnections(connections,now=Date.now()){return (connections||[]).filter(c=>c.status==='active'&&Number.isFinite(Date.parse(c.expires_at))&&Date.parse(c.expires_at)>now);}
export function latestDrafts(submissions){const projects=new Map();for(const draft of submissions){const prior=projects.get(draft.project_id);if(!prior||draft.revision>prior.revision)projects.set(draft.project_id,draft);}return [...projects.values()];}
export function pendingPair(storage,now=Date.now()) {try{const saved=JSON.parse(storage?.getItem(PAIR_STORAGE)||'null');if(!saved||!Number.isFinite(saved.expires)||saved.expires<=now||saved.expires>now+600000)return null;return parsePairing(`https://slop.game/mcp/pair#id=${saved.id}&code=${saved.code}`);}catch{return null;}}
export function savePendingPair(storage,pair,now=Date.now()){try{if(pair)storage?.setItem(PAIR_STORAGE,JSON.stringify({...pair,expires:now+600000}));else storage?.removeItem(PAIR_STORAGE);return !!storage;}catch{return false;}}
// Sequence reads and keep every async UI commit within its mounted account.
export function createPortalScope(){let epoch=0,read=0,operation=null;return {invalidate(){epoch++;read++;operation=null;},read(){const e=epoch,r=++read;return ()=>epoch===e&&read===r;},begin(key){if(operation)return null;const token={key,epoch};operation=token;read++;return {current:()=>operation===token&&epoch===token.epoch,finish(){if(operation===token)operation=null;}};},get busy(){return operation!==null;}};}
export function portalDraftView(draft,data){const view=mcpDraftPublicationView(draft,data?.gameStates,data?.liveGames?.[draft.project_id]);const automatic=['requested','recording','publishing'].includes(draft.publication?.status);const published=view.state==='published',review=view.state==='pending_review';return {...view,automatic,group:published?'published':review?'review':'ready',badge:published?'Published':review?'In review':automatic?'Publishing':draft.publication?.status==='failed'?'Needs attention':view.update?'Update ready':'Ready to playtest',action:view.update?'Playtest update':'Playtest & publish',locked:view.locked||automatic};}
export function validatePortalPayload(connections,drafts){if(!Array.isArray(connections)||connections.length>100||!connections.every(validConnection)||!Array.isArray(drafts)||drafts.length>50||!drafts.every(validDraft))throw new SlopError('invalid_response');}
