import React,{useEffect,useRef,useState} from 'react';
import {useAuth} from '../auth.jsx';
import {creator,privatePreview,publishRevision} from '../lib/creator.js';
import {creatorRevisionId} from '../lib/creator-contracts.js';
import {encodeCapture} from '../lib/capture.js';
import {UUID} from '../lib/contracts.js';
import {claimGameName,myGameName} from '../lib/game-name-claims.js';
import {suggestGameName,validGameName} from '../lib/game-links.js';
import {Button,Empty,IconButton,Loading,Modal,Notice,SectionHeading,Slop,useAsync} from '../components/ui.jsx';
import {Icon} from '../components/Icon.jsx';
import './build.css';
import SlopMotion from '../components/SlopMotion.jsx';
import {GamePlayer} from '../components/GamePlayer.jsx';
import {buildIdeaRoute,clearBuildIdea,readBuildIdea,saveBuildIdea} from '../lib/build-draft.js';
const samples=['A tiny frog hopping between floating islands','Drift a toy car through a midnight city','A cozy puzzle about sorting little planets'];
const modelNames={'gpt-5.6-sol':'Sol','gpt-6-astra':'Astra'};
export default function Build({params}){
 const{user,requireAuth}=useAuth();
 const[initialIdea]=useState(()=>params.has('idea')?readBuildIdea({ownerId:user?.id||null,id:params.get('idea')}):null);
 const ideaId=useRef(initialIdea?.id||null);
 const[prompt,setPrompt]=useState(initialIdea?.prompt||''),[model,setModel]=useState('gpt-5.6-sol'),[dimension,setDimension]=useState('auto'),[project,setProject]=useState(null),[run,setRun]=useState(null),[revision,setRevision]=useState(null),[details,setDetails]=useState(null),[error,setError]=useState(null),[busy,setBusy]=useState(false),[pending,setPending]=useState(null),[preview,setPreview]=useState(null),[failures,setFailures]=useState(0),[message,setMessage]=useState('');
 const[lookBrief,setLookBrief]=useState(''),[controlBrief,setControlBrief]=useState('');
 const routeEpoch=useRef(0);const stateRef=useRef({});stateRef.current={project,run,revision};
 const remix=UUID.test(params.get('remix'))?params.get('remix'):null;
 useEffect(()=>{if(!project&&ideaId.current)saveBuildIdea(prompt,{ownerId:user?.id||null,id:ideaId.current,remixId:remix});},[prompt,project,user?.id,remix]);
 useEffect(()=>{if(initialIdea)document.getElementById('game-idea')?.focus();},[]);
 const history=useAsync(async()=>user?(await creator('/projects')).projects:[],[user?.id]);
 const capabilityScope=[user?.id,project?.id,project?.head_revision_id,remix].join(':');
 const capabilities=useAsync(async()=>user?{...await creator('/capabilities'+(project?`?project_id=${project.id}`:remix?`?source_game_id=${remix}`:'')),context:capabilityScope}:null,[capabilityScope]);
 const scopedCapabilities=!capabilities.loading&&capabilities.data?.context===capabilityScope?capabilities.data:null;
 useEffect(()=>{routeEpoch.current++;setProject(null);setRun(null);setRevision(null);setDetails(null);setPreview(null);setError(null);setPending(null);setBusy(false);setFailures(0);
  try{const saved=JSON.parse(sessionStorage.getItem(`slop.pending-build.${user?.id}`));if(saved?.owner===user?.id&&saved?.body?.request_id)setPending(saved.body);}catch{}
 },[user?.id]);
 useEffect(()=>{if(scopedCapabilities?.models?.length){const selected=scopedCapabilities.models.find(m=>m.id===model&&m.available);if(!selected){const available=scopedCapabilities.models.find(m=>m.available);if(available)setModel(available.id);}}},[scopedCapabilities]);
 async function chooseProject(id){const epoch=++routeEpoch.current;setBusy(true);setError(null);setPreview(null);setRevision(null);setFailures(0);try{const data=await creator(`/projects/${id}`);if(epoch!==routeEpoch.current)return;setProject(data.project);setDetails(data);setRun(data.active_run||null);const revisionId=creatorRevisionId(data.project,data.active_run);if(revisionId){const r=await creator(`/revisions/${revisionId}`);if(epoch===routeEpoch.current)setRevision(r.revision);}}catch(e){if(epoch===routeEpoch.current)setError(e);}finally{if(epoch===routeEpoch.current)setBusy(false);}}
 async function acceptRun(next){
  const epoch=routeEpoch.current;
  const data=await creator(`/projects/${next.project_id}`);if(epoch!==routeEpoch.current)return;
  const id=creatorRevisionId(data.project,next);
  let accepted=stateRef.current.revision;
  if(id&&(accepted?.id!==id||next.state==='ready')){const r=await creator(`/revisions/${id}`);if(epoch!==routeEpoch.current)return;accepted=r.revision;}
  setRun(next);setProject(data.project);setDetails(data);setRevision(id?accepted:null);
  if(next.state==='ready')setMessage('Your game is ready to playtest or publish.');
  history.refresh();
 }
 async function submit(e,retry=false){e?.preventDefault();if(!retry&&!prompt.trim())return;
  if(!user){
   const idea=saveBuildIdea(prompt,{id:ideaId.current||undefined,remixId:remix,awaitingAuth:true});
   if(!idea){setError(new Error('Your browser couldn’t save your idea before sign-in. Enable tab storage and try again.'));return;}
   ideaId.current=idea.id;location.hash=buildIdeaRoute(idea);requireAuth();return;
  }
  if(!requireAuth())return;setBusy(true);setError(null);setMessage('');const epoch=routeEpoch.current;
  const body=retry?pending:{request_id:crypto.randomUUID(),prompt:project?prompt.trim():[prompt.trim(),lookBrief.trim()&&`Visual style: ${lookBrief.trim()}`,controlBrief.trim()&&`Controls: ${controlBrief.trim()}`].filter(Boolean).join('\n\n'),model,dimension,...(project?{project_id:project.id,...(project.head_revision_id?{base_revision_id:project.head_revision_id}:{})}:remix?{source_game_id:remix}:{})};
  if(!body){setBusy(false);return;}if(body.prompt.length>12000){setError(new Error('Shorten your idea or details to fit 12,000 characters.'));setBusy(false);return;}setPending(body);sessionStorage.setItem(`slop.pending-build.${user.id}`,JSON.stringify({owner:user.id,body}));
  try{const data=await creator('/runs',body);if(epoch!==routeEpoch.current)return;setPending(null);sessionStorage.removeItem(`slop.pending-build.${user.id}`);clearBuildIdea({ownerId:user.id,id:ideaId.current});ideaId.current=null;setPrompt('');setFailures(0);await acceptRun(data.run);capabilities.refresh();}
  catch(e){if(epoch===routeEpoch.current){setError(e);if(e.status>=400&&e.status<500&&!['request_conflict','run_busy'].includes(e.code)){setPending(null);sessionStorage.removeItem(`slop.pending-build.${user.id}`);}}}
  finally{if(epoch===routeEpoch.current)setBusy(false);}
 }
 useEffect(()=>{
  if(!user||!run||!['queued','working'].includes(run.state)||busy||failures>=3)return;
  const epoch=routeEpoch.current;let alive=true;let timer;
  const tick=async()=>{if(document.hidden){timer=setTimeout(tick,2000);return;}try{const data=await creator(`/runs/${run.id}/advance`,{expected_version:run.version});if(alive&&epoch===routeEpoch.current){setFailures(0);await acceptRun(data.run);}}catch(e){if(alive&&epoch===routeEpoch.current){setFailures(v=>v+1);setError(e);}}};
  timer=setTimeout(tick,Math.max(1200,Math.min(run.poll_after_ms||2000,15000))*(failures+1));return()=>{alive=false;clearTimeout(timer);};
 },[run?.id,run?.version,run?.state,user?.id,busy,failures]);
 async function refresh(){if(!project)return;await chooseProject(project.id);}
 async function cancel(){if(!run)return;setBusy(true);setError(null);try{const data=await creator(`/runs/${run.id}/cancel`,{expected_version:run.version});await acceptRun(data.run);}catch(e){setError(e);}finally{setBusy(false);}}
 async function playtest(publish=false){if(!revision||!project)return;setBusy(true);setError(null);const epoch=routeEpoch.current;try{const prepared=await privatePreview(project,revision);if(epoch===routeEpoch.current)setPreview({...prepared,project,revision,publish,run});}catch(e){if(epoch===routeEpoch.current)setError(e);}finally{if(epoch===routeEpoch.current)setBusy(false);}}
 async function feedback(observations){const data=await creator(`/runs/${run.id}/feedback`,{expected_version:run.version,revision_digest:revision.digest,observations});await acceptRun(data.run);setPreview(null);setMessage(data.run.state==='ready'?'Your game is ready to playtest or publish.':'Slop is using your playtest to improve this version.');}
 const active=run&&['queued','working','waiting_feedback','uncertain'].includes(run.state);
 const selectedModel=scopedCapabilities?.models?.find(m=>m.id===model);
 return <div className={`build-page ${project?'has-project':'new-project'}`}>
 <div className="builder-heading"><h1>{project?project.title:'Build'}</h1><a className="inline-link" href="#/connect"><Icon name="connect" size={18}/>Connect a coding app <Icon name="arrow" size={17}/></a></div>
 <div className="builder-layout"><section className="builder-main">
 <div className="workshop-compose">
  {!project&&<div className="workshop-welcome"><div className="workshop-monitor" aria-hidden="true"><div className="workshop-monitor-screen"><SlopMotion variant="slop-morph-showcase" poster="slop-morph-poster" alt=""/></div><span/></div><h2>What do you want<br/>to make?</h2></div>}
  <form className="workshop-form" onSubmit={submit}>
   <label className={project?'workshop-prompt-label':'sr-only'} htmlFor="game-idea">{project?'What would you like to change?':'Describe your game'}</label>
   <textarea id="game-idea" value={prompt} onChange={e=>setPrompt(e.target.value)} rows={4} maxLength={10000} placeholder={project?'Make the jumps higher. Add another level…':remix?'Describe your take on this game…':'Describe a game you wish existed…'} disabled={busy||!!pending||!!active}/>
   {!project&&<details className="workshop-details"><summary>Style and controls <Icon name="plus" size={16}/></summary><div className="workshop-options"><fieldset><legend>Game format</legend><div className="dimension-picker">{[['auto','Let Slop choose'],['2d','2D'],['3d','3D']].map(([id,label])=><button key={id} type="button" aria-pressed={dimension===id} disabled={busy||!!active} onClick={()=>setDimension(id)}>{label}</button>)}</div></fieldset><label htmlFor="game-look">How should it look?<textarea id="game-look" rows={2} value={lookBrief} onChange={e=>setLookBrief(e.target.value)} maxLength={900} disabled={busy||!!active} placeholder="A clay desert at dusk…"/></label><label htmlFor="game-controls">How do you play?<textarea id="game-controls" rows={2} value={controlBrief} onChange={e=>setControlBrief(e.target.value)} maxLength={900} disabled={busy||!!active} placeholder="Tap to jump, drag to steer…"/></label></div></details>}
   <div className="workshop-toolbar"><div className="workshop-model"><label><span className="sr-only">Creation model</span><Icon name="spark" size={16}/><select aria-label="Creation model" value={model} onChange={e=>setModel(e.target.value)} disabled={busy||!!active}>{(scopedCapabilities?.models||[{id:'gpt-5.6-sol',available:true},{id:'gpt-6-astra',available:true}]).map(m=><option key={m.id} value={m.id} disabled={!m.available}>{modelNames[m.id]||m.id}{m.remaining_today!=null?` · ${m.remaining_today} left today`:''}</option>)}</select></label><span className="workshop-price">{user?(selectedModel?.coin_cost!=null?(selectedModel.coin_cost===0?(selectedModel.first_refine_eligible?'First change free':'Free'):`${selectedModel.coin_cost} coins`):'Checking allowance…'):'Use your Slop account'}</span></div><Button icon="arrow" disabled={busy||!!active||!!pending||!prompt.trim()||(!!user&&(!selectedModel?.available||!scopedCapabilities?.available))}>{busy?'Working…':project?'Update game':'Build game'}</Button></div>
  </form>
  {!project&&<div className="workshop-starters">{samples.map((sample,i)=><button key={sample} onClick={()=>setPrompt(sample)} disabled={!!active||!!pending}><Icon name={['play','spark','build'][i]} size={15}/>{['Planet hopping','Midnight racing','A puzzle game'][i]}</button>)}</div>}
 </div>
 <Notice error={error} onRetry={project?refresh:undefined}/><Notice error={capabilities.error} onRetry={capabilities.refresh}/>{user&&scopedCapabilities&&!scopedCapabilities.available&&<p className="notice">{scopedCapabilities.reason||'Creation is not available for this account right now. Your existing projects are still here.'}</p>}{pending&&<div className="panel retry-build"><h3>Confirming your build request</h3><p>We kept the original request so retrying won’t create a second paid build.</p><Button disabled={busy} onClick={e=>submit(e,true)}>Retry the same request</Button></div>}{message&&<p className="success" role="status">{message}</p>}
 {run&&<div className={`run-panel panel state-${run.state}`}><Slop className={run.state==='working'?'loading-slop':''} alt=""/><div><h2>{({queued:'Your build is queued.',working:'Building your game…',waiting_feedback:'Your game is ready to test.',ready:'Saved and ready to play.',failed:'This idea needs another try.',cancelled:'Build stopped.',uncertain:'Let’s check where your build landed.'})[run.state]||'Your game is taking shape.'}</h2><p>{run.state==='ready'?'Your playtested version is saved and ready to share.':run.progress?.message||run.error?.message||'Your work is saved to your Slop account.'}</p>{['queued','working'].includes(run.state)&&<Button variant="small secondary" disabled={busy} onClick={cancel}>Stop building</Button>}{run.state==='uncertain'&&<Button variant="small secondary" onClick={refresh}>Check build status</Button>}</div></div>}
 {revision&&<div className="revision-panel panel"><div><p className="fine">Version {revision.number}</p><h2>{revision.title||project?.title}</h2><p>{revision.summary}</p></div><div className="revision-actions"><Button icon="play" onClick={()=>playtest()} disabled={busy}>Playtest this version</Button>{project?.head_revision_id===revision.id&&<Button icon="share" variant="secondary" onClick={()=>playtest(true)} disabled={busy}>Publish game</Button>}</div></div>}
 {details?.messages?.length>0&&<div className="build-conversation">{details.messages.map((m,i)=><article key={m.id||i} className={`build-message ${m.role==='user'?'from-you':'from-slop'}`}><strong>{m.role==='user'?'You':'Slop'}</strong><p>{m.content||m.text||m.message}</p></article>)}</div>}
 </section><aside className="project-sidebar"><div className="project-top"><h2>Your projects</h2><IconButton name="plus" label="Start a new project" disabled={busy||!!pending} onClick={()=>{routeEpoch.current++;setProject(null);setDetails(null);setRun(null);setRevision(null);setPreview(null);setPrompt('');setLookBrief('');setControlBrief('');setError(null);location.hash='/build';}}/></div>{!user?<div className="project-empty"><Slop body="triangle" color="lavender" alt=""/><p>Sign in to see your games and projects.</p></div>:history.loading?<p className="muted">Loading your projects…</p>:history.error?<Notice error={history.error} onRetry={history.refresh}/>:history.data?.length?<div className="project-list">{history.data.map(p=><button className={project?.id===p.id?'active':''} key={p.id} onClick={()=>chooseProject(p.id)} disabled={busy||!!pending}><Icon name="code"/><span><strong>{p.title||'Untitled idea'}</strong><small>{p.updated_at?new Date(p.updated_at).toLocaleDateString():'Saved in Slop'}</small></span><Icon name="chevron" size={16}/></button>)}</div>:<p className="muted">Your saved projects appear here.</p>}<a className="desktop-invite" href="#/connect"><Icon name="connect" size={28}/><h3>Have a coding app?</h3><p>Connect Codex, Cursor or Claude Code to build here.</p><span>Connect a coding app <Icon name="arrow" size={16}/></span></a></aside></div>
 {preview&&<Playtest preview={preview} onClose={()=>setPreview(null)} onFeedback={feedback} onPublished={receipt=>{setPreview(null);setMessage(receipt.status==='published'?'Your game is live in Slop!':'Your game has been submitted for review. It will appear in the feed after approval.');refresh();}}/>}</div>;
}
function Playtest({preview,onClose,onFeedback,onPublished}){
 const player=useRef(null),captureRequest=useRef(null),alive=useRef(true);const[error,setError]=useState(null),[captured,setCaptured]=useState(null),[busy,setBusy]=useState(false),[recorded,setRecorded]=useState(null),[stage,setStage]=useState(''),[notes,setNotes]=useState(''),[title,setTitle]=useState(preview.revision.title||preview.project.title||''),[tagline,setTagline]=useState('');
 const[gameName,setGameName]=useState(()=>suggestGameName(preview.revision.title||preview.project.title)),[claimed,setClaimed]=useState(false),[nameLoading,setNameLoading]=useState(preview.publish);
 useEffect(()=>{if(!preview.publish)return;let active=true;myGameName(preview.project.game_slug).then(value=>{if(active&&value){setGameName(value.name);setClaimed(true);}}).catch(e=>{if(active)setError(e);}).finally(()=>{if(active)setNameLoading(false);});return()=>{active=false;};},[preview.project.game_slug,preview.publish]);
 useEffect(()=>()=>{alive.current=false;if(captureRequest.current){clearTimeout(captureRequest.current.timer);captureRequest.current.reject(new Error('Playtest closed.'));captureRequest.current=null;}},[]);
 function capture(){return new Promise((resolve,reject)=>{const request=crypto.randomUUID();const timer=setTimeout(()=>{captureRequest.current=null;reject(new Error('The game did not return a frame. Wait until it is playing, then retry.'));},6000);captureRequest.current={request,resolve,reject,timer};player.current?.capture(request);});}
 function event(e){if(['webCaptureResult','webCaptureError'].includes(e.type)&&e.request===captureRequest.current?.request){const pending=captureRequest.current;clearTimeout(pending.timer);captureRequest.current=null;e.type==='webCaptureError'?pending.reject(new Error(e.message)):pending.resolve(e);}}
 async function record(){setBusy(true);setError(null);try{const frames=[];for(let i=0;i<12;i++){if(!alive.current)return;setStage(`Recording gameplay · ${i+1}/12`);const frame=await capture();if(frame.errors?.length)throw new Error(frame.errors[0]);frames.push(frame.data);await new Promise(r=>setTimeout(r,200));}if(!alive.current)return;setStage('Making your gameplay preview…');const data=await encodeCapture(frames);if(alive.current){setRecorded(data);setCaptured(frames[0]);setStage('Your real gameplay preview is ready.');}}catch(e){if(alive.current)setError(e);}finally{if(alive.current)setBusy(false);}}
 async function feedback(ready){setBusy(true);setError(null);try{const frame=await capture();if(!alive.current)return;setCaptured(frame.data);await onFeedback({ready,errors:ready?(frame.errors||[]):[notes||'The game needs another pass.'],notes,frames:1});}catch(e){if(alive.current)setError(e);}finally{if(alive.current)setBusy(false);}}
 return <Modal title={preview.publish?'Publish your game':'Playtest your game'} onClose={()=>{if(!busy)onClose();}} className="playtest-modal"><div className="playtest-layout"><GamePlayer ref={player} url={preview.url} preview title={preview.revision.title} onEvent={event}/><div className="playtest-review"><p className="fine">Version {preview.revision.number} · Private preview</p><h2>{preview.publish?'Publish your game.':'How did it feel?'}</h2><p>{preview.publish?'Play while we record a short clip. Your cover and preview come from this exact game.':'Give your game a proper try. Move around, score a point, and see if it feels like your idea.'}</p>{preview.publish?<><label>Game title<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={80}/></label><label>Game link<div className="game-name-field"><span>slop.game/</span><input aria-label="Unique game name" value={gameName} disabled={claimed||nameLoading||busy} onChange={e=>setGameName(e.target.value.toLowerCase())} minLength={3} maxLength={50} placeholder="your-game-name"/></div></label><p className="fine">{claimed?'This name belongs to your game.':'Choose a unique name. Only your account can use it for this game.'}</p><label>Description<textarea rows={2} maxLength={240} value={tagline} onChange={e=>setTagline(e.target.value)}/></label><Button variant="secondary" icon="play" disabled={busy} onClick={record}>{recorded?'Record again':'Record gameplay preview'}</Button>{stage&&<p role="status">{stage}</p>}{captured&&<img className="captured-cover" src={captured} alt="Captured frame from your game"/>}<Button icon="share" disabled={busy||nameLoading||!recorded||!title.trim()||!validGameName(gameName)} onClick={async()=>{setBusy(true);setError(null);try{if(!claimed){setStage('Reserving your game link…');await claimGameName(preview.project.game_slug,gameName);setClaimed(true);}const receipt=await publishRevision({project:preview.project,revision:preview.revision,title:title.trim(),tagline:tagline.trim(),prompt:'Created with Slop',...recorded,onStage:setStage});onPublished(receipt);}catch(e){setError(e);}finally{if(alive.current)setBusy(false);}}}>{busy?'Saving your game…':'Submit game for review'}</Button><p className="fine">Publishing uses the same checks as the mobile app. A confirmed review receipt comes before your game joins the public feed.</p></>:preview.run?.state==='waiting_feedback'?<><label>Playtest notes<textarea rows={3} maxLength={3000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What worked? What could be better?"/></label><Button icon="check" disabled={busy} onClick={()=>feedback(true)}>Feels good. Keep this version.</Button><Button variant="secondary" disabled={busy||!notes.trim()} onClick={()=>feedback(false)}>Use my notes to improve it</Button></>:<p className="fine">This version is already saved. Return to the workshop to make a change or publish.</p>}<Notice error={error}/></div></div></Modal>;
}
