import React,{useEffect,useState} from 'react';
import {useAuth} from '../auth.jsx';
import {mcpRequest} from '../lib/supabase.js';
import {parsePairing,trustedEntry,UUID,DIGEST,SlopError} from '../lib/contracts.js';
import {Button,CopyButton,Loading,Modal,Notice,SectionHeading,useAsync} from '../components/ui.jsx';
import {Icon} from '../components/Icon.jsx';
import './connect.css';
import {McpDraftReview} from '../components/McpDraftReview.jsx';
import {mcpGameStates} from '../lib/mcp-publication.js';
const packageUrl='https://slop.game/downloads/slop-game-mcp-0.3.0.tgz';
const config=JSON.stringify({mcpServers:{slop:{type:'stdio',command:'npx',args:['--yes',`--package=${packageUrl}`,'slop-mcp']}}},null,2);
const openCodeConfig=JSON.stringify({$schema:'https://opencode.ai/config.json',mcp:{slop:{type:'local',command:['npx','--yes',`--package=${packageUrl}`,'slop-mcp'],enabled:true,timeout:60000}}},null,2);
const clients={
 codex:{name:'Codex',command:`codex mcp add slop -- npx --yes --package=${packageUrl} slop-mcp`,lead:'Run this command in your computer’s terminal.',copy:'Copy Codex command',check:'Restart Codex, then check Slop in its MCP settings. You can also run codex mcp list.',docs:'https://learn.chatgpt.com/docs/extend/mcp?surface=cli'},
 opencode:{name:'OpenCode',command:openCodeConfig,lead:'Merge this Slop entry into your OpenCode configuration, keeping your existing settings.',copy:'Copy OpenCode configuration',check:'Restart OpenCode, open its MCP servers, and check that Slop is enabled.',docs:'https://opencode.ai/v2/docs/mcp-servers'},
 openchamber:{name:'OpenChamber',command:`npx --yes --package=${packageUrl} slop-mcp`,lead:'Open Settings → MCP, add a personal local server named slop, and use this command.',copy:'Copy OpenChamber command',check:'Save the server, leave it enabled, and check that Slop appears in your available tools.',docs:'https://docs.openchamber.dev/mcp/'},
 cursor:{name:'Cursor',command:config,lead:'Merge this Slop entry into ~/.cursor/mcp.json, keeping your existing servers.',copy:'Copy Cursor configuration',check:'Open Cursor’s MCP settings and enable Slop.',docs:'https://cursor.com/docs/mcp'},
 claude:{name:'Claude Code',command:`claude mcp add --transport stdio --scope user slop -- npx --yes --package=${packageUrl} slop-mcp`,lead:'Run this command in your computer’s terminal.',copy:'Copy Claude Code command',check:'Restart Claude Code, then run /mcp to check that Slop is connected.',docs:'https://code.claude.com/docs/en/mcp'},
 local:{name:'Local agent',command:config,lead:'Add this local STDIO server to any MCP-compatible agent host. The model can be local; its host starts Slop.',copy:'Copy generic MCP configuration',check:'Restart the host and check that all six Slop tools appear. If it cannot find npx, replace npx with the result of command -v npx.',docs:'https://github.com/robbygat/slop-web/tree/main/mcp',guide:'Slop local-agent guide'},
};
const pairStorage='slop.pending-pair.v1';
function validConnection(c){return UUID.test(c?.connection_id)&&typeof c.client_name==='string'&&c.client_name.length>0&&c.client_name.length<=60&&['pending','active','expired','revoked'].includes(c.status)&&Array.isArray(c.scopes)&&c.scopes.length===2&&c.scopes.includes('drafts:send')&&c.scopes.includes('drafts:status');}
function futureDate(value){return typeof value==='string'&&Number.isFinite(Date.parse(value))&&Date.parse(value)>Date.now();}
function validDraft(d){return UUID.test(d?.submission_id)&&UUID.test(d.project_id)&&DIGEST.test(d.digest)&&Number.isSafeInteger(d.revision)&&d.revision>0&&typeof d.name==='string'&&d.name.length>0&&d.name.length<=80&&/^mcp-[a-f0-9]{32}$/.test(d.slug)&&(!d.target_platform||['mobile','desktop','cross-platform'].includes(d.target_platform))&&['awaiting_confirmation','validating','ready'].includes(d.status);}
export default function Connect({params}){
 const{user,signIn,requireAuth}=useAuth();
 const[link,setLink]=useState(''),[pairing,setPairing]=useState(null),[review,setReview]=useState(null),[error,setError]=useState(null),[busy,setBusy]=useState(null),[preview,setPreview]=useState(null),[setup,setSetup]=useState(false),[message,setMessage]=useState('');
 const[setupAgent,setSetupAgent]=useState('codex');
 const[setupTarget,setSetupTarget]=useState('cross-platform');
 const client=clients[setupAgent];
 const firstGamePrompt=`Check slop_connection_status. If connected, call slop_game_template with target_platform: "${setupTarget}" and keep its slop.js unchanged. Make a small responsive ${setupTarget} game using its ready, score, finished, restart, pause, pointer, keyboard and touch lifecycle as appropriate. Call slop_send_draft with the same target_platform and all files. Keep it private for my playtest and tell me when it awaits my confirmation.`;
 const loadAccount=async()=>{if(!user)return {connections:[],submissions:[]};const[c,d]=await Promise.all([mcpRequest('slop-mcp','/connections'),mcpRequest('slop-mcp','/drafts')]);if(!Array.isArray(c.connections)||c.connections.length>100||!c.connections.every(validConnection)||!Array.isArray(d.submissions)||d.submissions.length>50||!d.submissions.every(validDraft))throw new SlopError('invalid_response');const submissions=d.submissions.filter(item=>!d.submissions.some(other=>other.project_id===item.project_id&&other.revision>item.revision));const gameStates=await mcpGameStates(submissions);return {connections:c.connections,submissions,gameStates};};
 const account=useAsync(loadAccount,[user?.id]);
 useEffect(()=>{if(!user)return;let alive=true,timer;const tick=async()=>{if(!alive)return;if(!document.hidden&&!busy&&!preview){try{const next=await loadAccount();if(alive)account.setData(next);}catch{}}if(alive)timer=setTimeout(tick,8000);};timer=setTimeout(tick,8000);return()=>{alive=false;clearTimeout(timer);};},[user?.id,busy,preview]);
 useEffect(()=>{
  const incoming=parsePairing(`https://slop.game/mcp/pair#id=${params.get('id')||''}&code=${params.get('code')||''}`);
  let saved;try{saved=JSON.parse(sessionStorage.getItem(pairStorage));}catch{}
  if(incoming){setPairing(incoming);sessionStorage.setItem(pairStorage,JSON.stringify({...incoming,expires:Date.now()+600000}));history.replaceState(null,'','/#/connect');}
  else if(saved?.expires>Date.now()){const p=parsePairing(`https://slop.game/mcp/pair#id=${saved.id}&code=${saved.code}`);if(p)setPairing(p);}
 },[]);
 useEffect(()=>{setReview(null);setPreview(null);setError(null);},[user?.id]);
 async function inspect(p=pairing){if(!p||!requireAuth())return;setBusy('review');setError(null);try{const c=await mcpRequest('slop-mcp',`/pair/review?pairing_id=${p.id}&code=${p.code}`);if(!validConnection(c)||c.pairing_id!==p.id)throw new SlopError('invalid_response');setReview(c);}catch(e){setError(e);}finally{setBusy(null);}}
 async function approve(){if(!pairing||!review)return;setBusy('approve');setError(null);try{const c=await mcpRequest('slop-mcp','/pair/confirm',{body:{pairing_id:pairing.id,code:pairing.code}});if(!validConnection(c)||c.pairing_id!==pairing.id||c.status!=='active'||!futureDate(c.expires_at)||c.requires_confirmation!==false)throw new SlopError('invalid_response');setPairing(null);setReview(null);sessionStorage.removeItem(pairStorage);setMessage(`${c.client_name} is connected. Ask it to send your first game.`);account.refresh();}catch(e){setError(e);}finally{setBusy(null);}}
 async function openDraft(d){setBusy(d.submission_id);setError(null);try{if(!validDraft(d))throw new SlopError('invalid_response');const p=await mcpRequest('slop-mcp','/drafts/confirm',{body:{submission_id:d.submission_id,expected_digest:d.digest}});if(!validDraft(p)||p.status!=='ready'||p.submission_id!==d.submission_id||p.digest!==d.digest||p.slug!==d.slug||!UUID.test(p.game_id)||!trustedEntry(p.preview_url,{preview:true,slug:d.slug})||!futureDate(p.preview_expires_at))throw new SlopError('invalid_response');setPreview(p);account.refresh();}catch(e){setError(e);}finally{setBusy(null);}}
 async function revoke(c){setBusy(c.connection_id);setError(null);try{const r=await mcpRequest('slop-mcp','/connections/revoke',{body:{connection_id:c.connection_id}});if(r.connection_id!==c.connection_id||r.status!=='revoked')throw new SlopError('invalid_response');account.refresh();setMessage('Connection removed. This agent can no longer send drafts.');}catch(e){setError(e);}finally{setBusy(null);}}
 return <div className="connect-page"><header className="connect-heading"><h1>Connect your coding app.</h1><p>Make a game in Codex, OpenCode, OpenChamber, Cursor, Claude Code or another local MCP agent. Send it to Slop, review it, and play on the web or your phone.</p><div className="connect-client-actions">{Object.entries(clients).map(([id,c])=><Button key={id} icon="code" variant="secondary" onClick={()=>{setSetupAgent(id);setSetup(true);}}>{c.name}</Button>)}</div><p className="mcp-plain">Powered by MCP, a secure connection between your coding app and Slop.</p></header>
 <div className="step-row">{[['1','Choose your coding app','Use a hosted coding app or any local model inside an MCP-compatible host.'],['2','Connect your Slop account','Open the link or scan its QR with your phone camera. Approve once; draft delivery is headless after that.'],['3','Send a complete game','Choose Phone, Desktop, or Both. Slop.js fits the game and a moving GIF is required to publish.']].map(s=><div key={s[0]}><span>{s[0]}</span><div><h3>{s[1]}</h3><p>{s[2]}</p></div></div>)}</div>
 <Notice error={error}/>{message&&<p className="success" role="status">{message}</p>}
 <section className="pair-panel panel"><div><h2>Connect from this phone.</h2><p>Scan the QR with your phone camera and Slop.game opens the secure review here. Or paste the link from your coding app below.</p></div><form onSubmit={e=>{e.preventDefault();const p=parsePairing(link);if(!p){setError(new SlopError('invalid_pairing'));return;}setPairing(p);sessionStorage.setItem(pairStorage,JSON.stringify({...p,expires:Date.now()+600000}));inspect(p);}}><label>Connection link<input type="url" value={link} onChange={e=>setLink(e.target.value)} placeholder="https://api.slop.game/functions/v1/slop-mcp/authorize#…" required maxLength={240}/></label><Button variant="secondary" disabled={!!busy}>Review connection</Button></form></section>
 {pairing&&!review&&<div className="pair-pending panel"><Icon name="connect"/><div><h3>Finish connecting.</h3><p>{user?'Review the requested access before connecting.':'Sign in with the Slop account you want to connect.'}</p></div><Button onClick={()=>user?inspect():signIn()} disabled={!!busy}>{user?'Review connection':'Sign in to review'}</Button></div>}
 <div className="connect-columns"><section><SectionHeading title="From your computer" action={user&&<Button variant="small secondary" icon="refresh" onClick={account.refresh}>Refresh</Button>}/>{!user?<div className="connect-empty"><h3>Your games arrive here.</h3><p>Sign in to review the private drafts sent by your coding app.</p><Button onClick={signIn}>Sign in</Button></div>:account.loading?<Loading label="Checking your draft inbox…"/>:account.error?<Notice error={account.error} onRetry={account.refresh}/>:account.data?.submissions.length?<div className="draft-list">{account.data.submissions.map(d=><article className="draft-card" key={d.submission_id}><Icon name="play" size={22}/><div><h3>{d.name}</h3><span className="fine">Version {d.revision}</span><p>{({pending_review:'Submitted for review. Your game will appear in the feed once approved.',published:'Published. Your game is available on the web and in the app.',private:'This game is private.'})[account.data.gameStates?.[d.game_id]]||'Playtest this version, record a clip, and choose when to submit it for review.'}</p><Button variant="secondary small" icon="play" disabled={!!busy||['pending_review','published','rejected','private'].includes(account.data.gameStates?.[d.game_id])} onClick={()=>openDraft(d)}>{account.data.gameStates?.[d.game_id]==='pending_review'?'In review':account.data.gameStates?.[d.game_id]==='published'?'Published':busy===d.submission_id?'Preparing…':d.status==='ready'?'Playtest & publish':'Approve & playtest'}</Button></div></article>)}</div>:<div className="connect-empty"><h3>No drafts yet.</h3><p>Games sent by your coding app will appear here for you to review.</p></div>}</section>
 <section><SectionHeading title="Your connections"/>{account.data?.connections.filter(c=>c.status==='active').length?<div className="connection-list">{account.data.connections.filter(c=>c.status==='active').map(c=><div className="connection-card" key={c.connection_id}><Icon name="connect"/><div><h3>{c.client_name}</h3><p>Connected until {new Date(c.expires_at).toLocaleDateString()}</p></div><button className="text-button danger" disabled={!!busy} onClick={()=>revoke(c)}>Disconnect</button></div>)}</div>:<div className="panel connection-empty"><Icon name="connect" size={32}/><h3>No coding apps connected.</h3><p>Only apps you approve can send games to your account.</p></div>}<div className="permission-note"><Icon name="lock"/><p>Connections can send drafts and check their status. Your agent cannot spend coins, change your account, or publish games for you.</p></div></section></div>
 {setup&&<Modal title="Connect your coding app" onClose={()=>setSetup(false)} className="setup-modal"><p>Choose the app you use to make games. Then follow these three steps.</p><div className="segmented" role="group" aria-label="Choose your coding agent">{Object.entries(clients).map(([id,c])=><button key={id} type="button" aria-pressed={setupAgent===id} className={setupAgent===id?'active':''} onClick={()=>setSetupAgent(id)}>{c.name}</button>)}</div><h3>1. Add Slop to {client.name}</h3><p>{client.lead}</p><pre>{client.command}</pre><CopyButton value={client.command} label={client.copy}/><p>{client.check}</p><a className="inline-link" href={client.docs} target="_blank" rel="noreferrer">{client.guide||`Official ${client.name} setup guide`} <Icon name="arrow" size={16}/></a><h3>2. Connect your account</h3><blockquote>“Call slop_pair and show me the QR code and pairing link.”</blockquote><CopyButton value="Call slop_pair and show me the QR code and pairing link." label="Copy pairing prompt"/><p>Scan the QR with your phone camera. Slop.game opens the secure review page in your mobile browser so you can check the named agent and allow draft access. After this one-time approval, the local agent can send drafts headlessly for 30 days. Public release still requires you.</p><h3>3. Choose where it plays</h3><div className="mcp-target-picker" role="group" aria-label="Game target">{[['mobile','Phone'],['desktop','Desktop'],['cross-platform','Both']].map(([id,label])=><button key={id} type="button" aria-pressed={setupTarget===id} onClick={()=>setSetupTarget(id)}>{label}</button>)}</div><blockquote>“Build a {setupTarget} game with the Slop template and send it to my private playtest.”</blockquote><CopyButton value={firstGamePrompt} label="Copy first game prompt"/><p>The target is sealed into the draft. Slop.js provides the native lifecycle and responsive canvas. You play the exact build and record its required moving GIF before it can enter review.</p><details><summary>Advanced setup and requirements</summary><p>You’ll need Node.js 22.12 or later. This setup uses a local MCP connection on your computer.</p><pre>{config}</pre><CopyButton value={config} label="Copy MCP configuration"/><p>The local adapter stays silent while waiting for MCP messages; that is normal. If your host says it produced no output, use an absolute npx path and a 60-second startup timeout.</p><a href={packageUrl} download>Download the MCP package</a></details></Modal>}
 {review&&<Modal title="Connect this computer?" onClose={()=>{setReview(null);setError(null);}}><div className="review-identity"><Icon name="connect" size={36}/><div><h3>{review.client_name}</h3><p>Connecting to {user?.email}</p></div></div><p>Check that this is the coding app you just connected.</p><ul className="permission-list"><li><Icon name="check"/> Send private game drafts to your account</li><li><Icon name="check"/> Check the status of its own drafts</li><li><Icon name="lock"/> Every revision needs your confirmation</li></ul><p className="fine">Access expires in 30 days. You can disconnect at any time.</p><Notice error={error}/><Button className="full" disabled={!!busy} onClick={approve}>{busy==='approve'?'Connecting…':'Allow connection'}</Button></Modal>}
 {preview&&<McpDraftReview preview={preview} onClose={()=>setPreview(null)} onPublished={receipt=>{setPreview(null);setMessage(receipt.status==='published'?'Your game is published on the web and in the app.':'Your game was submitted for review. It will appear on the web and in the app once approved.');account.refresh();}}/>}
 </div>;
}
