import React,{useCallback,useEffect,useRef,useState} from 'react';
import {useAuth} from '../auth.jsx';
import {getSession,mcpRequest} from '../lib/supabase.js';
import {parsePairing,trustedEntry,UUID,SlopError} from '../lib/contracts.js';
import {Button,Loading,Modal,Notice} from '../components/ui.jsx';
import {Icon} from '../components/Icon.jsx';
import RobotPortrait from '../components/RobotPortrait.jsx';
import SlopMark from '../components/SlopMark.jsx';
import McpSetup from '../components/McpSetup.jsx';
import {McpDraftReview} from '../components/McpDraftReview.jsx';
import ManualPreviewRecorder from '../components/ManualPreviewRecorder.jsx';
import {mcpRecoveryError} from '../lib/mcp-publication-recovery.js';
import {mcpGameStates} from '../lib/mcp-publication.js';
import {mcpTargetLabel} from '../lib/mcp-platform.js';
import {mcpConnectionNotice} from '../lib/mcp-connection-notice.js';
import {createDraftPreparer} from '../lib/mcp-draft-preparation.js';
import {activeConnections,createPortalScope,latestDrafts,pendingPair,portalDraftView,savePendingPair,validConnection,validDraft,validatePortalPayload} from '../lib/mcp-portal.js';
import './connect.css';
import './creator-portal.css';

const future=value=>typeof value==='string'&&Number.isFinite(Date.parse(value))&&Date.parse(value)>Date.now();
const storage=()=>{try{return sessionStorage;}catch{return null;}};

function usePortalAccount(owner,scope,paused){
 const[data,setData]=useState(null),[loading,setLoading]=useState(!!owner),[error,setError]=useState(null);const mounted=useRef(true),inflight=useRef(0);
 const refresh=useCallback(async({quiet=false}={})=>{
  if(!owner)return;if(quiet&&(inflight.current||scope.busy))return;
  const current=scope.read();inflight.current++;if(!quiet)setLoading(true);setError(null);
  try{
   const expected=getSession();if(expected?.user?.id!==owner)throw new SlopError('account_changed');
   const[c,d]=await Promise.all([mcpRequest('slop-mcp','/connections'),mcpRequest('slop-mcp','/drafts')]);validatePortalPayload(c.connections,d.submissions);
   const gameStates=await mcpGameStates(d.submissions),liveGames={};
   for(const s of d.submissions){if(!['published','updating','pending_review'].includes(gameStates[s.game_id]))continue;const known=liveGames[s.project_id];if(!known||s.revision>known.revision)liveGames[s.project_id]={slug:s.slug,game_id:s.game_id,revision:s.revision,name:s.name,state:gameStates[s.game_id],digest:gameStates.digests?.[s.game_id]??null};}
   if(getSession()?.epoch!==expected.epoch||getSession()?.user?.id!==owner)throw new SlopError('account_changed');
   if(mounted.current&&current())setData({ownerId:owner,connections:c.connections,submissions:latestDrafts(d.submissions),gameStates,liveGames});
  }catch(e){if(mounted.current&&current())setError(mcpRecoveryError(e));}
  finally{inflight.current--;if(mounted.current&&current())setLoading(false);}
 },[owner,scope]);
 useEffect(()=>{mounted.current=true;void refresh();return()=>{mounted.current=false;scope.invalidate();};},[refresh,scope]);
 useEffect(()=>{if(!owner)return;const tick=()=>{if(!document.hidden&&!paused)void refresh({quiet:true});};const timer=setInterval(tick,10000);window.addEventListener('online',tick);document.addEventListener('visibilitychange',tick);return()=>{clearInterval(timer);window.removeEventListener('online',tick);document.removeEventListener('visibilitychange',tick);};},[owner,paused,refresh]);
 return {data:data?.ownerId===owner?data:null,loading,error,refresh};
}

export default function Connect({params}) {
 const{user,signIn,requireAuth}=useAuth();const scope=useRef(createPortalScope()).current;
 const preparer=useRef(null);if(!preparer.current)preparer.current=createDraftPreparer({request:mcpRequest});
 const[view,setView]=useState('inbox'),[filter,setFilter]=useState('all'),[setup,setSetup]=useState(false),[linkOpen,setLinkOpen]=useState(false),[link,setLink]=useState('');
 const[pairing,setPairing]=useState(null),[review,setReview]=useState(null),[error,setError]=useState(null),[busy,setBusy]=useState(null),[message,setMessage]=useState(''),[disconnect,setDisconnect]=useState(null);
 const[preview,setPreview]=useState(null),[recording,setRecording]=useState(null);
 const account=usePortalAccount(user?.id,scope,!!preview||!!recording),data=account.data;
 const active=activeConnections(data?.connections),drafts=data?.submissions||[];
 const cards=drafts.map(d=>({draft:d,view:portalDraftView(d,data)}));
 const status=typeof message==='string'?message:mcpConnectionNotice(message,data?.connections,user?.id);
 useEffect(()=>{
   const incoming=parsePairing(`https://slop.game/mcp/pair#id=${params.get('id')||''}&code=${params.get('code')||''}`),pair=incoming||pendingPair(storage());
   if(pair){setPairing(pair);setLinkOpen(true);if(incoming){savePendingPair(storage(),pair);history.replaceState(null,'','/#/connect');}}
 },[params.get('id'),params.get('code')]);
 async function perform(key,work){const operation=scope.begin(key);if(!operation)return;setBusy(key);setError(null);try{await work(operation.current);}catch(e){if(operation.current())setError(mcpRecoveryError(e));}finally{if(operation.current()){operation.finish();setBusy(null);void account.refresh();}}}
 function showPair(){setSetup(false);setLinkOpen(true);}
 async function inspect(pair=pairing){if(!pair||!requireAuth())return;await perform('inspect',async current=>{const c=await mcpRequest('slop-mcp',`/pair/review?pairing_id=${pair.id}&code=${pair.code}`);if(!validConnection(c)||c.pairing_id!==pair.id)throw new SlopError('invalid_response');if(current()){setReview(c);setLinkOpen(false);}});}
 async function approve(){if(!pairing||!review)return;await perform('approve',async current=>{const c=await mcpRequest('slop-mcp','/pair/confirm',{body:{pairing_id:pairing.id,code:pairing.code}});if(!validConnection(c)||c.pairing_id!==pairing.id||c.status!=='active'||!future(c.expires_at)||c.requires_confirmation!==false)throw new SlopError('invalid_response');if(current()){setPairing(null);setReview(null);savePendingPair(storage(),null);setMessage({connection_id:c.connection_id,owner_id:user.id});}});}
 async function openDraft(d){if(!requireAuth())return;await perform(d.submission_id,async current=>{if(!validDraft(d))throw new SlopError('invalid_response');const p=await preparer.current(d);if(!validDraft(p)||p.status!=='ready'||p.submission_id!==d.submission_id||p.digest!==d.digest||p.slug!==d.slug||!UUID.test(p.game_id)||!trustedEntry(p.preview_url,{preview:true,slug:d.slug})||!future(p.preview_expires_at))throw new SlopError('invalid_response');if(current()){const live=data.liveGames?.[d.project_id];setPreview(live&&live.game_id!==p.game_id?{...p,update_target:live}:p);}});}
 async function autoPublish(connection,enabled){await perform(connection.connection_id,async()=>{const result=await mcpRequest('slop-mcp','/connections/auto-publish',{body:{connection_id:connection.connection_id,enabled}});if(result.connection_id!==connection.connection_id||result.auto_publish!==enabled)throw new SlopError('invalid_response');});}
 async function revoke(){const connection=disconnect;if(!connection)return;await perform('disconnect',async current=>{const result=await mcpRequest('slop-mcp','/connections/revoke',{body:{connection_id:connection.connection_id}});if(result.connection_id!==connection.connection_id||result.status!=='revoked')throw new SlopError('invalid_response');if(current()){setDisconnect(null);setMessage(`${connection.client_name} is disconnected.`);}});}
 return <div className="creator-portal">
  <header className="studio-header studio-launch"><div><h1>Make your next<br/><em>favorite game.</em></h1><p>Bring your idea. Let your coding app build it.<br/>Play it here, then share it with everyone.</p><div className="studio-actions"><Button onClick={()=>user?setSetup(true):document.querySelector('.portal-guest-layout')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}>Let’s make something <Icon name="arrow" size={18}/></Button><button onClick={showPair}>Use a connection link</button></div></div><div className="studio-machine" aria-hidden="true"><span className="studio-cable cable-one"/><span className="studio-cable cable-two"/><span className="studio-code">{'{ }'}</span><SlopMark/><RobotPortrait shell="coin-op"/><span className="studio-play"><Icon name="play" fill="currentColor" size={36}/></span><span className="studio-machine-caption">A little idea. A whole new game.</span></div></header>
  {user&&<div className="portal-workspace-bar"><div role="group" aria-label="Creator workspace"><button aria-pressed={view==='inbox'} onClick={()=>setView('inbox')}>Game inbox <span>{drafts.length}</span></button><button aria-pressed={view==='connections'} onClick={()=>setView('connections')}>Connections <span>{active.length}</span></button></div><div className={`portal-status ${active.length?'is-connected':''}`}><i/>{!user?'Sign in to sync':account.loading&&!data?'Checking connection…':active.length?`${active.length} app${active.length===1?'':'s'} connected`:'No app connected'}</div></div>}
  <Notice error={error||account.error} onRetry={()=>account.refresh()}/>{status&&<p className="success" role="status">{status}</p>}
  {pairing&&!review&&!linkOpen&&<div className="portal-pair-reminder"><Icon name="connect"/><span>Your connection is ready to review.</span><Button onClick={()=>user?inspect():signIn()} disabled={!!busy}>{user?'Review access':'Sign in to connect'}</Button></div>}
  {!user?<div className="portal-guest-layout"><McpSetup onPair={showPair}/><aside className="portal-inbox-empty"><RobotPortrait shell="liftoff" alt=""/><h2>Your games<br/>land here.</h2><p>Sign in to the same Slop account you use in the app. Your agent’s games arrive ready to playtest.</p><Button onClick={signIn}>Sign in to your inbox <Icon name="arrow" size={17}/></Button><div className="portal-mini-flow"><span>01 BUILD</span><span>02 PLAYTEST</span><span>03 PUBLISH</span></div></aside></div>:
  view==='inbox'?<section className="portal-inbox"><div className="portal-inbox-heading"><div><h2>Your next release.</h2><p>Private until you publish. Every version stays connected to its game.</p></div><Button variant="secondary small" icon="refresh" disabled={!!busy||account.loading} onClick={()=>account.refresh()}>Refresh</Button></div><div className="inbox-filters" role="group" aria-label="Filter games">{[['all','All games'],['ready','To playtest'],['review','In review'],['published','Published']].map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}{id!=='all'&&<span>{cards.filter(c=>c.view.group===id).length}</span>}</button>)}</div>
   {account.loading&&!data?<Loading label="Opening your game inbox…"/>:cards.filter(c=>filter==='all'||c.view.group===filter).length?<div className="portal-draft-grid">{cards.filter(c=>filter==='all'||c.view.group===filter).map(({draft:d,view:v},i)=><article className="portal-draft" key={d.submission_id}><div className={`portal-draft-art tone-${i%3}`}><span>{mcpTargetLabel(d.target_platform)}</span><RobotPortrait shell={['coin-op','liftoff','blocky'][i%3]} alt=""/><span className={`draft-state state-${v.group}`}>{v.badge}</span></div><div className="portal-draft-body"><span className="draft-version">VERSION {d.revision}</span><h3>{d.name}</h3><p>{v.label||(v.update?'A new version of your existing game.':v.state==='private'?'This game is private.':v.state==='rejected'?'This version needs changes. Send an update from your agent.':'Give it a spin. Your real gameplay becomes the preview.')}</p>{v.state==='published'?<a className="button secondary full" href={`#/home?game=${encodeURIComponent(v.applied?data.liveGames[d.project_id].slug:d.slug)}`}>Open published game <Icon name="arrow" size={17}/></a>:<Button className="full" disabled={!!busy||v.locked} onClick={()=>openDraft(d)}>{busy===d.submission_id?'Preparing your game…':v.locked?v.badge:v.action}<Icon name="play" size={17}/></Button>}{busy===d.submission_id&&<p className="draft-progress" role="status">Checking files and opening your private preview. Larger games may take a moment.</p>}{v.published?.hasVideo===false&&<Button variant="secondary full" disabled={!!busy} onClick={()=>setRecording(v.published)}>Finish video preview</Button>}</div></article>)}</div>:<div className="portal-empty"><RobotPortrait shell="core" alt=""/><h3>{filter==='all'?'Your first game starts with an idea.':'No games in this view yet.'}</h3><p>{filter==='all'?'Ask your coding app to make a game and send it to Slop. It arrives here, ready for you.':'Your game status updates automatically.'}</p><Button onClick={()=>setSetup(true)}>{active.length?'Get a starter message':'Connect your coding app'}</Button></div>}
  </section>:<section className="portal-connections"><div className="portal-inbox-heading"><div><h2>Your creative toolkit.</h2><p>Choose which coding apps can send games to your Slop.</p></div><Button onClick={()=>setSetup(true)} icon="plus">Add app</Button></div>{active.length?<div className="portal-connection-list">{active.map(c=><article key={c.connection_id}><div className="connection-app-icon"><Icon name="code"/></div><div className="connection-main"><h3>{c.client_name}<span>Connected</span></h3><p>Access ends {new Date(c.expires_at).toLocaleDateString()}</p><label className="portal-auto-publish"><input type="checkbox" checked={c.auto_publish===true} disabled={!!busy} onChange={e=>autoPublish(c,e.target.checked)}/><span><strong>Publish automatically</strong><small>{c.auto_publish?'This app can publish its games. Slop captures their previews.':'You review and publish every game yourself.'}</small></span></label></div><button className="text-button" disabled={!!busy} onClick={()=>setDisconnect(c)}>Disconnect</button></article>)}</div>:<div className="portal-empty"><RobotPortrait shell="clicky" alt=""/><h3>Make room for your favorite coding app.</h3><p>Connect once. Your agent sends its games straight to your inbox.</p><Button onClick={()=>setSetup(true)}>Connect an app</Button></div>}<p className="portal-permissions"><Icon name="lock" size={16}/>Connected apps can send drafts. They can’t spend coins or change your account.</p></section>}
  {setup&&<Modal title="Connect your coding app" onClose={()=>setSetup(false)} className="portal-setup-modal"><McpSetup connected={active.length>0} onPair={showPair}/></Modal>}
  {linkOpen&&<Modal title="Connect your coding app" onClose={()=>setLinkOpen(false)} className="portal-pair-modal"><RobotPortrait shell="clicky" alt=""/><h3>Let’s make the connection.</h3><p>Paste the connection link your agent gave you. You’ll review its access before allowing it.</p><form onSubmit={e=>{e.preventDefault();const pair=parsePairing(link);if(!pair){setError(new SlopError('invalid_pairing'));return;}setPairing(pair);savePendingPair(storage(),pair);if(user)inspect(pair);else signIn();}}><label>Connection link<input type="url" value={link} onChange={e=>setLink(e.target.value)} placeholder="https://api.slop.game/…" required maxLength={2000} autoComplete="off"/></label><Button className="full" disabled={!!busy}>{busy==='inspect'?'Checking link…':user?'Review connection':'Sign in to connect'}</Button></form>{pairing&&<Button variant="secondary full" disabled={!!busy} onClick={()=>user?inspect():signIn()}>{user?'Review your saved connection':'Sign in for your saved connection'}</Button>}<Notice error={error}/></Modal>}
  {review&&<Modal title="Allow this app to connect?" onClose={()=>{if(!busy)setReview(null);}} className="portal-permission-modal"><div className="review-identity"><Icon name="connect" size={30}/><div><h3>{review.client_name}</h3><p>{user?.email}</p></div></div><p>Make sure this is the coding app you just set up.</p><ul className="permission-list"><li><Icon name="check"/>Send private games to your inbox</li><li><Icon name="check"/>Check the status of its own games</li><li><Icon name="lock"/>You control publishing</li></ul><p className="fine">Access lasts 30 days. Disconnect at any time.</p><Notice error={error}/><Button className="full" disabled={!!busy} onClick={approve}>{busy==='approve'?'Connecting…':'Allow connection'}</Button></Modal>}
  {disconnect&&<Modal title={`Disconnect ${disconnect.client_name}?`} onClose={()=>{if(!busy)setDisconnect(null);}}><p>Your games stay in Slop. This app will need a new connection to send more games.</p><Notice error={error}/><Button variant="secondary full" disabled={!!busy} onClick={revoke}>{busy?'Disconnecting…':'Disconnect app'}</Button></Modal>}
  {recording&&<ManualPreviewRecorder key={`${user?.id}:${recording.id}:${recording.releaseKey}`} game={recording} onClose={()=>{setRecording(null);void account.refresh();}}/>}
  {preview&&<McpDraftReview preview={preview} onClose={()=>setPreview(null)} onPublished={receipt=>{setPreview(null);setMessage(receipt.status==='published'?(receipt.videoPending?'Your game is published. Finish its video preview from the inbox.':'Your game and video preview are published.'):'Your game is in review. It joins the public feed after approval.');void account.refresh();}}/>}
 </div>;
}
