import React,{useRef,useState} from 'react';
import {Button,CopyButton} from './ui.jsx';
import {Icon} from './Icon.jsx';
import {CREATE_SPARKS,createBuildPrompt} from '../lib/create-brief.js';

export default function CreateLaunchpad({connected=false,onSetup}) {
 const [spark,setSpark]=useState('score'),[idea,setIdea]=useState(CREATE_SPARKS[0].idea),[target,setTarget]=useState('cross-platform');
 const input=useRef(null),prompt=createBuildPrompt({idea,target});
 function choose(s){setSpark(s.id);setIdea(s.idea);if(s.id==='custom')input.current?.focus();}
 return <section className="create-launchpad" id="create-launchpad" aria-labelledby="create-launchpad-title">
  <div className="create-launchpad-heading"><div><span className="create-kicker"><Icon name="spark" size={16}/> The next great game starts small</span><h2 id="create-launchpad-title" tabIndex={-1}>What should we play next?</h2><p>Pick a spark. Make it yours. Your coding app takes it from there.</p></div><span className="create-private"><Icon name="lock" size={14}/> Private playtest first</span></div>
  <div className="create-launchpad-grid">
   <div className="create-idea"><div className="create-spark-picker" role="group" aria-label="Choose a game idea">{CREATE_SPARKS.map(s=><button key={s.id} className={`create-spark tone-${s.tone}`} aria-pressed={spark===s.id} onClick={()=>choose(s)}><span className="create-spark-icon"><Icon name={s.icon} size={22}/></span><span><strong>{s.title}</strong><small>{s.line}</small></span>{spark===s.id&&<Icon name="check" size={15}/>}</button>)}</div><label htmlFor="create-game-idea">Your game idea<textarea ref={input} id="create-game-idea" value={idea} maxLength={1200} rows={4} onChange={e=>setIdea(e.target.value)} placeholder="A robot, one simple rule, and a twist nobody expects…" aria-describedby="create-idea-hint"/></label><p id="create-idea-hint" className="create-idea-hint">One clear action + one unexpected twist. Start there.</p></div>
   <aside className="create-handoff"><div><span className="create-kicker">Your agent handoff</span><h3>Make the first<br/>version playable.</h3><p>A clear brief, real controls, and a game you can try before it goes live.</p></div><fieldset className="create-target"><legend>Where should it play?</legend><div role="group" aria-label="Game platform">{[['mobile','Phone'],['desktop','Desktop'],['cross-platform','Both']].map(([id,label])=><button key={id} aria-pressed={target===id} onClick={()=>setTarget(id)}>{label}</button>)}</div></fieldset><ol className="create-handoff-path"><li><span>1</span><div><strong>Build in your coding app</strong><small>Paste the message. Let your agent make it.</small></div></li><li><span>2</span><div><strong>Playtest in your inbox</strong><small>Try the real game and send back feedback.</small></div></li><li><span>3</span><div><strong>Share when you love it</strong><small>Your gameplay becomes its video preview.</small></div></li></ol><details className="create-prompt-preview"><summary>Read the build message</summary><pre>{prompt||'Add your game idea to make a build message.'}</pre></details><div className="create-handoff-actions">{prompt?<CopyButton value={prompt} label="Copy build message"/>:<Button disabled icon="copy">Add your idea first</Button>}{!connected&&<button className="create-setup-link" onClick={onSetup}>Set up a coding app <Icon name="arrow" size={15}/></button>}</div><p className="create-handoff-note">{connected?'Paste into your connected coding app. The next draft arrives in your inbox.':'Have Slop connected already? Copy the message. Otherwise, set up your app first.'}</p></aside>
  </div>
 </section>;
}
