import React,{useEffect,useRef,useState} from 'react';
import {GamePlayer} from './GamePlayer.jsx';
import {Button,Modal,Notice} from './ui.jsx';
import {encodeCapture} from '../lib/capture.js';
import {submitMcpPublication} from '../lib/mcp-publication.js';
import {claimGameName,myGameName,previewGameName} from '../lib/game-name-claims.js';
import {validGameName} from '../lib/game-links.js';
import {mcpTargetLabel} from '../lib/mcp-platform.js';
import './mcp-draft-review.css';
export function McpDraftReview({preview,onClose,onPublished}){
 const player=useRef(null),pending=useRef(null),alive=useRef(true);
 const[busy,setBusy]=useState(false),[error,setError]=useState(null),[stage,setStage]=useState(''),[recorded,setRecorded]=useState(null),[image,setImage]=useState(null),[clip,setClip]=useState(null),[title,setTitle]=useState(preview.name||''),[description,setDescription]=useState(preview.description||''),[gameName,setGameName]=useState(''),[claimed,setClaimed]=useState(false),[nameEdited,setNameEdited]=useState(false),[nameLoading,setNameLoading]=useState(true);
 const captureReady=!!recorded?.gif?.length&&!!recorded?.cover?.length&&recorded.frameCount>=3;
 useEffect(()=>{if(claimed||nameEdited)return;let active=true;setNameLoading(true);const timer=setTimeout(()=>{myGameName(preview.slug).then(name=>name||previewGameName(preview.slug,title)).then(name=>{if(active&&name){setGameName(name.name);setClaimed(name.claimed===true);}}).catch(e=>{if(active)setError(e);}).finally(()=>{if(active)setNameLoading(false);});},200);return()=>{active=false;clearTimeout(timer);};},[preview.slug,title,claimed,nameEdited]);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;if(pending.current){clearTimeout(pending.current.timer);pending.current.reject(new Error('Playtest closed.'));pending.current=null;}};},[]);
 useEffect(()=>{if(!recorded)return;const readers=[[recorded.gif,'image/gif',setClip],[recorded.cover,'image/jpeg',setImage]].map(([bytes,type,setValue])=>{const reader=new FileReader();reader.onload=()=>{if(alive.current)setValue(reader.result);};reader.readAsDataURL(new Blob([bytes],{type}));return reader;});return()=>{for(const reader of readers)reader.onload=null;};},[recorded]);
 function capture(){return new Promise((resolve,reject)=>{const request=crypto.randomUUID(),timer=setTimeout(()=>{pending.current=null;reject(new Error('The game did not return a frame. Start playing, then record again.'));},6000);pending.current={request,timer,resolve,reject};player.current?.capture(request);});}
 function event(e){if(!['webCaptureResult','webCaptureError'].includes(e.type)||e.request!==pending.current?.request)return;const p=pending.current;clearTimeout(p.timer);pending.current=null;e.type==='webCaptureError'?p.reject(new Error(e.message)):p.resolve(e);}
 async function record(){setBusy(true);setError(null);try{const frames=[];for(let i=0;i<12;i++){if(!alive.current)return;setStage(`Recording gameplay · ${i+1}/12`);const frame=await capture();if(frame.errors?.length)throw new Error(frame.errors[0]);frames.push(frame.data);await new Promise(r=>setTimeout(r,200));}if(!alive.current)return;setStage('Preparing the cover and clip…');const data=await encodeCapture(frames);if(alive.current){setRecorded(data);setStage('Your gameplay preview is ready.');}}catch(e){if(alive.current)setError(e);}finally{if(alive.current)setBusy(false);}}
 async function publish(){setBusy(true);setError(null);try{if(!claimed){setStage('Reserving your game link…');await claimGameName(preview.slug,gameName);if(!alive.current)return;setClaimed(true);}const receipt=await submitMcpPublication({preview,title:title.trim(),tagline:description.trim(),...recorded,onStage:value=>{if(alive.current)setStage(value);}});if(alive.current)onPublished(receipt);}catch(e){if(alive.current)setError(e);}finally{if(alive.current)setBusy(false);}}
 return <Modal title={preview.name||'Your game draft'} onClose={()=>{if(!busy)onClose();}} className="mcp-playtest-modal"><div className="mcp-playtest-layout"><GamePlayer ref={player} url={preview.preview_url} preview title={preview.name} onEvent={event}/><div className="mcp-publication"><h2>Play it. Make it yours.</h2><p>Your coding app sent this private version. Play it first, then record the gameplay GIF required for every published game.</p><div className="mcp-target"><span>Built for</span><strong>{mcpTargetLabel(preview.target_platform)}</strong></div><label>Game title<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={80} disabled={busy}/></label><label>Your permanent game link<div className="mcp-game-name"><span>slop.game/</span><input aria-label="Unique game name" value={gameName} onChange={e=>{setNameEdited(true);setGameName(e.target.value.toLowerCase());}} minLength={3} maxLength={50} disabled={claimed||nameLoading||busy} placeholder="your-game-name"/></div></label><p className="fine">{claimed?'This permanent link belongs to your game.':'People will use this address to open your game. Its display title can still change later.'}</p><label>Description<textarea rows={2} maxLength={240} value={description} onChange={e=>setDescription(e.target.value)} disabled={busy}/></label><Button icon="play" variant="secondary" disabled={busy} onClick={record}>{recorded?'Record again':'Record gameplay GIF'}</Button>{stage&&<p role="status">{stage}</p>}{image&&<div className="mcp-capture-preview"><figure><img className="mcp-captured-cover" src={image} alt="A real frame captured from your game"/><figcaption>Cover</figcaption></figure>{clip&&<figure><img className="mcp-captured-cover" src={clip} alt="Recorded gameplay GIF"/><figcaption>Moving GIF · {recorded.frameCount} frames</figcaption></figure>}</div>}<Button icon="share" disabled={busy||nameLoading||!captureReady||!title.trim()||!validGameName(gameName)} onClick={publish}>Submit game for review</Button><p className="fine">The website attaches this GIF through the same game-preview service as the mobile app. Submission stays locked until the clip is ready.</p><Notice error={error}/></div></div></Modal>;
}
