import React,{useState} from 'react';
import {Button,CopyButton} from './ui.jsx';
import {Icon} from './Icon.jsx';
export const packageUrl='https://slop.game/downloads/slop-game-mcp-0.5.2.tgz';
const config=JSON.stringify({mcpServers:{slop:{type:'stdio',command:'npx',args:['--yes',`--package=${packageUrl}`,'slop-mcp']}}},null,2);
const openCodeConfig=JSON.stringify({$schema:'https://opencode.ai/config.json',mcp:{slop:{type:'local',command:['npx','--yes',`--package=${packageUrl}`,'slop-mcp'],enabled:true,timeout:60000}}},null,2);
const clients={
 codex:{name:'Codex',letter:'C',command:`codex mcp add slop -- npx --yes --package=${packageUrl} slop-mcp`,lead:'Paste this into your computer’s terminal.',check:'Then restart Codex.',docs:'https://learn.chatgpt.com/docs/extend/mcp?surface=cli'},
 claude:{name:'Claude Code',letter:'✳',command:`claude mcp add --transport stdio --scope user slop -- npx --yes --package=${packageUrl} slop-mcp`,lead:'Paste this into your computer’s terminal.',check:'Then restart Claude Code.',docs:'https://code.claude.com/docs/en/mcp'},
 cursor:{name:'Cursor',letter:'↗',command:config,lead:'Add this server to ~/.cursor/mcp.json. Keep your other servers.',check:'Enable Slop in Cursor’s MCP settings.',docs:'https://cursor.com/docs/mcp'},
 opencode:{name:'OpenCode',letter:'O',command:openCodeConfig,lead:'Add this server to your OpenCode settings. Keep your other servers.',check:'Then restart OpenCode.',docs:'https://opencode.ai/v2/docs/mcp-servers'},
 openchamber:{name:'OpenChamber',letter:'◎',command:`npx --yes --package=${packageUrl} slop-mcp`,lead:'In Settings → MCP, add a server called slop with this command.',check:'Save it and leave it enabled.',docs:'https://docs.openchamber.dev/mcp/'},
 other:{name:'Other app',letter:'+',command:config,lead:'Add this server to your app’s MCP configuration.',check:'Then restart your app.',docs:'https://github.com/robbygat/slop-web/tree/main/mcp'},
};
export default function McpSetup({connected=false,onPair}) {
 const[step,setStep]=useState(0),[agent,setAgent]=useState('codex'),[target,setTarget]=useState('mobile');const client=clients[agent];
 const pairPrompt='Connect me to Slop. Use the slop_pair tool and show me the link and QR code.';
 const words={mobile:'phone',desktop:'computer','cross-platform':'phone and computer'};
 const prompt=`Make me a ${words[target]} game and send it to Slop. Use slop_game_template with target_platform "${target}", build a fun game, check it with slop_check_bundle, then send it with slop_send_draft.`;
 return <div className="mcp-setup-guide"><div className="setup-progress" role="group" aria-label="Connection setup steps">{['Add Slop','Connect','Make a game'].map((label,i)=><button key={label} onClick={()=>setStep(i)} aria-current={step===i?'step':undefined}><span>{i+1}</span>{label}</button>)}</div>
 {step===0?<section className="setup-content"><h2>Pick your coding app.</h2><p>One quick setup. Then create from the app you already use.</p><div className="mcp-client-grid" role="group" aria-label="Choose your coding app">{Object.entries(clients).map(([id,c])=><button key={id} onClick={()=>setAgent(id)} aria-pressed={agent===id}><b>{c.letter}</b><span>{c.name}</span>{agent===id&&<Icon name="check" size={14}/>}</button>)}</div><div className="setup-command"><div><span>Add Slop to {client.name}</span><CopyButton value={client.command} label="Copy setup"/></div><pre>{client.command}</pre></div><p className="setup-instruction">{client.lead} {client.check}</p><div className="setup-footer"><a href={client.docs} target="_blank" rel="noreferrer" className="text-arrow">App instructions <Icon name="arrow" size={16}/></a><Button onClick={()=>setStep(1)}>Next: connect <Icon name="arrow" size={17}/></Button></div></section>:
 step===1?<section className="setup-content"><h2>Give your agent a way in.</h2><p>Ask {client.name} to connect you to Slop. It will give you a link or QR code.</p><div className="setup-prompt"><span>Connect me to Slop.</span><CopyButton value={pairPrompt} label="Copy message"/></div><ol className="pair-instructions"><li>Open the link from your agent.</li><li>Sign in to your Slop account.</li><li>Review the app’s name and allow the connection.</li></ol><div className={`setup-connection-proof ${connected?'connected':''}`}><i/>{connected?'Your coding app is connected.':'A connection appears here after you approve it.'}</div><div className="setup-footer"><button className="text-arrow" onClick={onPair}>I have a connection link <Icon name="arrow" size={16}/></button><Button onClick={()=>setStep(2)}>{connected?'Make your first game':'See how to make a game'}<Icon name="arrow" size={17}/></Button></div></section>:
 <section className="setup-content"><h2>Your idea. Your agent. Your game.</h2><p>Tell your coding app what you want to play. It builds the game and sends it to your inbox.</p><div className="mcp-target-picker" role="group" aria-label="Where it plays">{[['mobile','Phone'],['desktop','Computer'],['cross-platform','Both']].map(([id,label])=><button key={id} aria-pressed={target===id} onClick={()=>setTarget(id)}>{label}</button>)}</div><div className="setup-prompt"><span>Make me a {words[target]} game and send it to Slop.</span><CopyButton value={prompt} label="Copy starter message"/></div><div className="setup-next"><Icon name="play"/><div><strong>Play it here. Publish when it’s ready.</strong><p>Slop records your gameplay for the cover and video preview. You control what goes live.</p></div></div><button className="text-arrow" onClick={()=>setStep(0)}>Back to setup <Icon name="arrow" size={16}/></button></section>}
 <details className="mcp-troubleshooting"><summary>Setup not working?</summary><p>Use Node.js 22.12 or newer, then restart your coding app after adding Slop. If <code>npx</code> is missing, use its full path from <code>command -v npx</code>. Allow 60 seconds for the server to start.</p><p>On a phone? Send these setup instructions to the computer running your coding app, then return here to playtest.</p><a className="text-arrow" href={packageUrl} download>Download the MCP package <Icon name="download" size={16}/></a></details>
 </div>;
}
