import React,{Suspense,lazy,useEffect,useState} from 'react';
import {useAuth} from './auth.jsx';
import {Icon} from './components/Icon.jsx';
import {Button,Loading,Slop} from './components/ui.jsx';
import Play from './pages/Play.jsx';
import {Appearance} from './theme.jsx';
import {gameNameFromPath} from './lib/game-links.js';
const Feed=lazy(()=>import('./pages/Feed.jsx'));
const Build=lazy(()=>import('./pages/Build.jsx')),Connect=lazy(()=>import('./pages/Connect.jsx')),Social=lazy(()=>import('./pages/Social.jsx')),Shop=lazy(()=>import('./pages/Shop.jsx')),You=lazy(()=>import('./pages/You.jsx')),Download=lazy(()=>import('./pages/Download.jsx')),Settings=lazy(()=>import('./pages/You.jsx').then(m=>({default:m.Settings})));
const tabs=[['home','Home','home'],['feed','For you','play'],['build','Build','build'],['social','Social','social'],['shop','Shop','shop'],['you','You','user']];
function getRoute(){const hash=location.hash.replace(/^#\/?/,'');const[path,query='']=hash.split('?');const params=new URLSearchParams(query),name=gameNameFromPath(location.pathname)||(/^\/(?:g|r|play|games)\/([A-Za-z0-9][A-Za-z0-9_-]{0,159})\/?$/.exec(location.pathname)?.[1]||null);if(!hash&&name)params.set('game',name);return {path:path==='play'?'home':path||'home',params};}
export default function App(){const[route,setRoute]=useState(getRoute),[search,setSearch]=useState(''),[term,setTerm]=useState('');const{user,profile,signIn}=useAuth();
 useEffect(()=>{const update=()=>{setRoute(getRoute());window.scrollTo({top:0});};window.addEventListener('hashchange',update);window.addEventListener('popstate',update);return()=>{window.removeEventListener('hashchange',update);window.removeEventListener('popstate',update);};},[]);
 useEffect(()=>{const t=setTimeout(()=>setSearch(term),250);return()=>clearTimeout(t);},[term]);
 useEffect(()=>{document.title=({home:'Home',feed:'For you',build:'Build',social:'Social',shop:'Shop',you:'You',connect:'Connect an agent',download:'Get the app',settings:'Your account'})[route.path]+' · Slop';},[route.path]);
 const navigation=(mobile=false)=><nav aria-label={mobile?'Mobile navigation':'Main navigation'}>{tabs.map(([id,label,icon])=><a href={`#/${id}`} key={id} className={`nav-item ${route.path===id?'active':''} nav-${id}`} aria-label={label} title={label} aria-current={route.path===id?'page':undefined}>{id==='feed'?<span className="nav-play-word">play</span>:id==='you'?<Slop look={profile?.slop_look} avatar={profile?.avatar_url} alt=""/>:<Icon name={icon}/>}</a>)}</nav>;
 return <><a className="skip-link" href="#main" onClick={e=>{e.preventDefault();document.getElementById('main')?.focus();}}>Skip to content</a>
 <div className="app-shell"><header className="topbar"><a className="mobile-brand brand" href="#/home"><span>Slop.game</span></a><div className="desktop-navigation">{navigation()}</div><div className="topbar-actions"><Appearance/><a className="topbar-connect" href="#/connect" aria-label="Connect a coding agent"><Icon name="connect"/></a><a className="app-download-link" href="#/download"><Icon name="download" size={18}/><span>Get the app</span></a>{user?<a className="account-chip" href="#/you"><Slop look={profile?.slop_look} avatar={profile?.avatar_url} alt=""/><span>{profile?.username||'Your Slop'}</span></a>:<Button variant="small dark" onClick={signIn}>Sign in</Button>}</div></header><main id="main" className={`main page-${route.path}`} tabIndex={-1}><Suspense key={user?.id||'guest'} fallback={<Loading/>}>{route.path==='home'?<Play params={route.params} search={search} term={term} setSearch={setTerm}/>:route.path==='feed'?<Feed/>:route.path==='build'?<Build params={route.params}/>:route.path==='connect'?<Connect params={route.params}/>:route.path==='social'?<Social/>:route.path==='shop'?<Shop/>:route.path==='you'?<You/>:route.path==='download'?<Download/>:route.path==='settings'?<Settings params={route.params}/>:<div className="empty"><Slop/><h1>Page not found.</h1><a className="button" href="#/home">Back to Home</a></div>}</Suspense></main><footer className="footer"><nav aria-label="Footer"><a href="#/download">Get the app</a><a href="#/connect">Connect a coding app</a><a href="/privacy.html">Privacy</a><a href="/terms.html">Terms</a><a href="/support.html">Support</a></nav><a className="company-link" href="https://aislopinc.com" target="_blank" rel="noopener noreferrer">© {new Date().getFullYear()} AI Slop Inc.</a></footer></div><div className="mobile-nav">{navigation(true)}</div></>;
}
