import React,{useEffect,useRef,useState} from 'react';
import {Icon} from './components/Icon.jsx';
const modes=['light','dark','system'];
export function Appearance({compact=false}){
 const menu=useRef(null),[open,setOpen]=useState(false);
 useEffect(()=>{if(!open)return;const close=e=>{if(!menu.current?.contains(e.target))setOpen(false);};const escape=e=>{if(e.key==='Escape'){setOpen(false);menu.current?.querySelector('button')?.focus();}};document.addEventListener('pointerdown',close);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',escape);};},[open]);
 const[mode,setMode]=useState(()=>{try{return modes.includes(localStorage.getItem('slop.appearance'))?localStorage.getItem('slop.appearance'):'system';}catch{return 'system';}});
 useEffect(()=>{const sync=e=>{if(modes.includes(e.detail))setMode(e.detail);};window.addEventListener('slop-appearance-change',sync);return()=>window.removeEventListener('slop-appearance-change',sync);},[]);
 const choose=value=>{if(modes.includes(value)){setMode(value);window.dispatchEvent(new CustomEvent('slop-appearance-change',{detail:value}));}};
 useEffect(()=>{const media=matchMedia('(prefers-color-scheme: dark)');const apply=()=>{document.documentElement.dataset.theme=mode==='system'?(media.matches?'dark':'light'):mode;document.documentElement.style.colorScheme=document.documentElement.dataset.theme;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',document.documentElement.dataset.theme==='dark'?'#172019':'#faf9f0');};apply();try{localStorage.setItem('slop.appearance',mode);}catch{}media.addEventListener('change',apply);return()=>media.removeEventListener('change',apply);},[mode]);
 if(compact)return <div className="masthead-theme" ref={menu}><button className="theme-trigger" type="button" aria-label="Color theme" aria-expanded={open} aria-controls="header-appearance" onClick={()=>setOpen(v=>!v)}><Icon name={mode==='dark'?'moon':mode==='light'?'sun':'appearance'} size={20}/></button>{open&&<div className="theme-menu" id="header-appearance" role="group" aria-label="Color theme options">{modes.map(value=><button type="button" key={value} aria-pressed={mode===value} onClick={()=>{choose(value);setOpen(false);menu.current?.querySelector('button')?.focus();}}><Icon name={value==='dark'?'moon':value==='light'?'sun':'appearance'} size={17}/><span>{value==='system'?'Match device':value==='light'?'Light mode':'Dark mode'}</span>{mode===value&&<span className="theme-selected" aria-hidden="true">✓</span>}</button>)}</div>}</div>;
 return <div className="appearance-buttons" role="group" aria-label="Appearance">{modes.map(value=><button type="button" key={value} aria-label={value==='system'?'Use system appearance':`Use ${value} theme`} aria-pressed={mode===value} title={value==='system'?'System':value==='light'?'Light':'Dark'} onClick={()=>choose(value)}><Icon name={value==='dark'?'moon':value==='light'?'sun':'appearance'} size={17}/></button>)}</div>;
}
